name: Caddy Build-Latest

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.3.0
      with:
        go-version: '1'
        check-latest: true
        
    - name: Build
      run: |
        go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
        ~/go/bin/xcaddy build \
        --with github.com/caddyserver/forwardproxy
        chmod +x caddy
        tar zcvf ./caddy.tar.gz ./caddy
    - name: Output
      uses: actions/upload-artifact@v4
      with:
          name: Caddy
          path: ./caddy.tar.gz
          if-no-files-found: error
    
    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: Get Caddy Version
      id: cv
      run: |
        echo "::set-output name=cv::$(./caddy version | awk '{print $1}')"
        echo "::set-output name=gv::$(go version | awk '{print $3}')"
    
    - name: Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Caddy-Latest ${{ steps.cv.outputs.cv }} with ${{ steps.cv.outputs.gv }}
        tag_name: Latest-Other-${{ steps.date.outputs.date }}
        files: ./caddy.tar.gz
    - name: Delete Artifacts
      uses: geekyeggo/delete-artifact@v4
      with:
        name: |
          Caddy
